export interface BrazilStateOption {
  code: string;
  name: string;
}

export interface DialCountryOption {
  code: string;
  name: string;
  dialCode: string;
}

export const BRAZIL_STATE_OPTIONS: BrazilStateOption[] = [
  { code: "AC", name: "Acre" },
  { code: "AL", name: "Alagoas" },
  { code: "AP", name: "Amapa" },
  { code: "AM", name: "Amazonas" },
  { code: "BA", name: "Bahia" },
  { code: "CE", name: "Ceara" },
  { code: "DF", name: "Distrito Federal" },
  { code: "ES", name: "Espirito Santo" },
  { code: "GO", name: "Goias" },
  { code: "MA", name: "Maranhao" },
  { code: "MT", name: "Mato Grosso" },
  { code: "MS", name: "Mato Grosso do Sul" },
  { code: "MG", name: "Minas Gerais" },
  { code: "PA", name: "Para" },
  { code: "PB", name: "Paraiba" },
  { code: "PR", name: "Parana" },
  { code: "PE", name: "Pernambuco" },
  { code: "PI", name: "Piaui" },
  { code: "RJ", name: "Rio de Janeiro" },
  { code: "RN", name: "Rio Grande do Norte" },
  { code: "RS", name: "Rio Grande do Sul" },
  { code: "RO", name: "Rondonia" },
  { code: "RR", name: "Roraima" },
  { code: "SC", name: "Santa Catarina" },
  { code: "SP", name: "Sao Paulo" },
  { code: "SE", name: "Sergipe" },
  { code: "TO", name: "Tocantins" },
];

// Fallback minimo caso a API do IBGE esteja temporariamente indisponivel.
export const BRAZIL_CITY_FALLBACK_BY_STATE: Record<string, string[]> = {
  AC: ["Rio Branco"],
  AL: ["Maceio"],
  AP: ["Macapa"],
  AM: ["Manaus"],
  BA: ["Salvador"],
  CE: ["Fortaleza"],
  DF: ["Brasilia"],
  ES: ["Vitoria"],
  GO: ["Goiania"],
  MA: ["Sao Luis"],
  MT: ["Cuiaba"],
  MS: ["Campo Grande"],
  MG: ["Belo Horizonte"],
  PA: ["Belem"],
  PB: ["Joao Pessoa"],
  PR: ["Curitiba"],
  PE: ["Recife"],
  PI: ["Teresina"],
  RJ: ["Rio de Janeiro"],
  RN: ["Natal"],
  RS: ["Porto Alegre"],
  RO: ["Porto Velho"],
  RR: ["Boa Vista"],
  SC: ["Florianopolis"],
  SP: ["Sao Paulo"],
  SE: ["Aracaju"],
  TO: ["Palmas"],
};

export const COUNTRY_DIAL_OPTIONS: DialCountryOption[] = [
  { code: "BR", name: "Brasil", dialCode: "55" },
  { code: "AR", name: "Argentina", dialCode: "54" },
  { code: "BO", name: "Bolivia", dialCode: "591" },
  { code: "CA", name: "Canada", dialCode: "1" },
  { code: "CL", name: "Chile", dialCode: "56" },
  { code: "CO", name: "Colombia", dialCode: "57" },
  { code: "EC", name: "Equador", dialCode: "593" },
  { code: "ES", name: "Espanha", dialCode: "34" },
  { code: "FR", name: "Franca", dialCode: "33" },
  { code: "DE", name: "Alemanha", dialCode: "49" },
  { code: "IE", name: "Irlanda", dialCode: "353" },
  { code: "IT", name: "Italia", dialCode: "39" },
  { code: "JP", name: "Japao", dialCode: "81" },
  { code: "MX", name: "Mexico", dialCode: "52" },
  { code: "PY", name: "Paraguai", dialCode: "595" },
  { code: "PT", name: "Portugal", dialCode: "351" },
  { code: "PE", name: "Peru", dialCode: "51" },
  { code: "GB", name: "Reino Unido", dialCode: "44" },
  { code: "UY", name: "Uruguai", dialCode: "598" },
  { code: "US", name: "Estados Unidos", dialCode: "1" },
  { code: "VE", name: "Venezuela", dialCode: "58" },
];

export const PET_BREED_OPTIONS: string[] = [
  "SRD / Vira-lata",
  "Labrador Retriever",
  "Golden Retriever",
  "Pastor Alemao",
  "Border Collie",
  "Siberian Husky",
  "Bulldog Frances",
  "Pug",
  "Beagle",
  "Shih Tzu",
  "Pinscher",
  "Rottweiler",
  "Doberman",
  "Boxer",
  "Akita",
  "Chow Chow",
  "Dachshund (Salsicha)",
  "Maltese",
  "Yorkshire Terrier",
  "Poodle",
  "Poodle Toy",
  "Poodle Mini",
  "Spitz Alemao",
  "Basset Hound",
  "Cocker Spaniel",
  "Cavalier King Charles Spaniel",
  "Jack Russell Terrier",
  "Bull Terrier",
  "American Bully",
  "American Pit Bull Terrier",
  "Staffordshire Bull Terrier",
  "Boston Terrier",
  "Shiba Inu",
  "Weimaraner",
  "Dalmata",
  "Schnauzer Miniatura",
  "Schnauzer",
  "Schnauzer Gigante",
  "Fila Brasileiro",
  "Mastiff",
  "Great Dane",
  "Bernese Mountain Dog",
  "Samoieda",
  "Bichon Frise",
  "Lhasa Apso",
  "Papillon",
  "Whippet",
  "Greyhound",
  "Fox Paulistinha",
  "Bulldog Ingles",
  "Buldogue Campeiro",
  "Cane Corso",
  "Australian Shepherd",
  "Australian Cattle Dog",
  "Bloodhound",
  "Saint Bernard",
  "Terra Nova",
  "Cao de Agua Portugues",
  "Cao de Serra da Estrela",
  "Husky do Alasca",
  "Boiadeiro Bernes",
  "Corgi",
  "Chihuahua",
  "Havanes",
  "Pekines",
  "Setter Ingles",
  "Pointer",
  "Braco Alemao",
  "Vizsla",
  "Shar Pei",
  "Airedale Terrier",
  "Borzoi",
  "Basenji",
  "Maine Coon",
  "Persa",
  "Siamese",
  "Ragdoll",
  "Bengal",
  "Sphynx",
  "British Shorthair",
  "Scottish Fold",
  "Noruegues da Floresta",
  "Angora Turco",
  "Bombay",
  "Himalaio",
  "Abissinio",
  "Burmese",
  "American Shorthair",
  "Exotic Shorthair",
  "Azul Russo",
  "Savannah",
  "Cornish Rex",
  "Devon Rex",
  "Oriental Shorthair",
  "Balinese",
  "Sagrado da Birmania",
];
